return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "xml",
        "html",
        "css",
        "javascript",
        "dockerfile",
        "yaml",
        "toml",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "gowork",
        "jsdoc",
        "json",
        "jsonc",
        "json5",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "python",
        "regex",
        "vim",
        "vimdoc",
      },
    },
  },
}

